name: Run Python Bot

on: 
  push:
    branches: [main]

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      id: checkout
      uses: actions/checkout@v2

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.0'

    - name: Install dependencies
      id: install-deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run bot script
      id: run-bot
      run: |
        python bot.py

    - name: Post setup-python
      if: success()
      run: echo "Python setup and checkout completed successfully."

    - name: Post checkout repository
      if: success()
      run: echo "Repository checked out successfully."
