name: Run Python Bot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Memungkinkan pemicuan manual workflow dari GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.0'  # Ganti dengan versi Python yang sesuai

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run bot script
      run: |
        python bot.py
